apiVersion: v1
kind: Service
metadata:
  name: rumpi
  namespace: rumpi-ns
spec:
  ports:
  - port: 9001
    targetPort: 9001
  selector:
    app: rumpi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rumpi
  namespace: rumpi-ns
spec:
  selector:
    matchLabels:
      app: rumpi
  replicas: 1
  template:
    metadata:
      labels:
        app: rumpi
    spec:
      containers:
      - name: rumpi
        image: wuriyanto/rumpi
        imagePullPolicy: always
        ports:
        - containerPort: 9001
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rumpi-ingress
  namespace: rumpi-ns
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: test.w1.thenets.org
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: rumpi
              port:
                number: 9001